### ISSUE TITLE
compilation fails due to missing libpfring

### ISSUE THREAD

**Issue by dpavlin** [cardigliano/bro-pf_ring#3]
I'm using pfring 7.1.0-1734 from Debian package and it doesn't include libpfring producing following error:

`PF_RING library and/or headers not found.`

I'm obviously doing something wrong, but I'm at loss what since documentation doesn't reference pfring 7 yet.

**Comment by cardigliano** [comment]
Please update to today's package and let us know if libpfring.so is installed under /usr/local/lib

**Comment by DigiAngel** [comment]
Same fam...my bro is compiled with --with-pcap=/opt/pfring and this appears to break when using bro-pkg:
~~~
error: failed to run tests for bro/ntop/bro-pf_ring: package build_command failed, see log in /root/.bro-pkg/logs/bro-pf_ring-build.log
-- Could NOT find PF_RING (missing:  PF_RING_LIBRARY PF_RING_INCLUDE_DIR)
~~~
manually compiling by adding:
~~~
--with-pfring=/opt/pfring
~~~
works however.
