### ISSUE TITLE
Update this plugin to compile on top of Zeek

### ISSUE THREAD

**Issue by cardigliano** [cardigliano/bro-pf_ring#5]

**Comment by andrewbeard** [comment]
I'm not going to pretend it's well tested, but I managed to get it to build with the changes here:
https://github.com/andrewbeard/zeek-pf_ring

**Comment by cardigliano** [comment]
Looks good, could se send a pull request to merge your fixes? Thank you!

**Comment by andrewbeard** [comment]
Just added https://github.com/ntop/bro-pf_ring/pull/6

**Comment by cardigliano** [comment]
Great, just merged, thank you! If you have more patches do not hesitate in sending them, they are really appreciated :-)
